version: '3'

services:
  mysqlcrud1:
    image: mysql:latest
    container_name: mysqlcrud1
    ports:
      - 3306:3306
#    restart: always
    environment:
      MYSQL_DATABASE: clientedb
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      
  backcrudcliente3:
    image: backcrudcliente3
    container_name: backcrudcliente3
    ports:
      - 8086:8086
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqlcrud1






